name: Ubuntu Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 9 * * 4'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: pip install --upgrade -r requirements.txt
      - name: Fetch upstream cheat sheets
        run: python lib/fetch.py fetch-all
      - name: Run bash tests
        run: bash tests/run-tests.sh
      - name: Run pytest
        run: pytest lib/

  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker and Docker-Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker
      - name: Build Docker images
        run: docker-compose build
      - name: List Docker images
        run: docker images
      - name: Run Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d
          # docker-compose -f docker-compose.yml -f docker-compose.debug.yml up -d
          docker-compose ps
          # Wait until the web server is up
          wget --timeout 3 --tries=5 --spider localhost:8002 2>&1 | grep -i http
          docker-compose logs --no-color
      - name: Run standalone tests
        run: CHEATLY_TEST_STANDALONE=NO bash tests/run-tests.sh
